server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kirnitskayamaria-star/Aston-2
          clone-on-start: true
          default-label: dev
          search-paths: HTTP_WEB/config-server/config-repo
